<div style="margin-left:auto;margin-right:auto;">
	<div style="float:left;">
		<?if ($this->message) :?>
		<div style="background-color:PaleGreen; width:100%;">
		<?=$this->message?>
		</div>
		<?endif;?>
		<?=$this->form->renderOpen()?>
		<fieldset><legend><?=__("Patient Information")?></legend>
		<div style="float:left;">
			<div>
			<div style="display:table-cell; vertical-align:middle; height:100px;">
				<img src="<?=$this->baseUrl?>/img/no-person-image.png">
			</div>
			</div>
		</div>
		<div style="float:left;">
			<div style="margin-left:10px;">
			<?foreach ($this->form->getErrorMessages() as $error) {?>
			<?=$error?>
			<?}?>
			<?=$this->form->personIdInput('FormHidden')?>
			<?=$this->form->formPerson->personIdInput('FormHidden')?>
			<div class="formRow">
			<?=$this->form->formPerson->lastName->renderLabel()?>
			<?=$this->form->formPerson->lastNameInput()?>
			</div>
			<div class="formRow">
			<?=$this->form->formPerson->firstName->renderLabel()?>
			<?=$this->form->formPerson->firstNameInput()?>
			</div>
			<div class="formRow">
			<?$this->form->formPerson->middleName->setAttrib('size',10)?>
			<?=$this->form->formPerson->middleName->renderLabel()?>
			<?=$this->form->formPerson->middleNameInput()?>
			</div>
			<br class="formRowDivider">
			<div class="formRow">
			<?$this->form->recordNumber->setAttrib('size',10)?>
			<?=$this->form->recordNumber->renderLabel()?>
			<?=$this->form->recordNumberInput()?>
			</div>
			<div class="formRow">
			<?=$this->form->formPerson->dateOfBirth->renderLabel()?>
			<?=$this->form->formPerson->dateOfBirthInput()?>
			</div>
			<div class="formRow">
			<?=$this->form->formPerson->gender->renderLabel()?>
			<?=$this->form->formPerson->genderInput('FormSelect',array("options" => Enumeration::getEnumArray('Gender','enumerationId')))?>
			</div>
			<div class="formRow">
			<?=$this->form->formPerson->maritalStatus->renderLabel()?>
			<?=$this->form->formPerson->maritalStatusInput('FormSelect',array("options" => Enumeration::getEnumArray('Marital Status','enumerationId')))?>
			</div>
			<div class="formRow">
			<?=$this->form->confidentiality->renderLabel()?>
			<?=$this->form->confidentialityInput('FormSelect',array("options" => Enumeration::getEnumArray('Confidentiality','enumerationId')))?>
			</div>
			<div class="formRow">
			<?=$this->form->formPerson->active->renderLabel()?>
			<?=$this->form->formPerson->activeInput('FormCheckbox', array('checked' => 1))?>
			</div>
			<br class="formRowDivider">
			<!--
			<div class="formRow">
			<?//=$this->form->formPerson->defaultInstitutionId->renderLabel()?>
			<?//=$this->form->formPerson->defaultInstitutionIdInput('FormSelect',array("options" => Location::getLocationArrayByType('INSTITUTION')))?>
			</div>
			<div class="formRow">
			<?//=$this->form->registrationLocationId->renderLabel()?>
			<?//=$this->form->registrationLocationIdInput('FormSelect',array("options" => Location::getLocationArrayByType('WARD')))?>
			</div>
			-->
			<div class="formRow">
			<?=$this->form->defaultProvider->renderLabel()?>
			<?=$this->form->defaultProviderInput('FormSelect',array("options" => Provider::getArray()))?>
			</div>
			</div>
			</fieldset>
			<fieldset><legend>Home Address</legend>
			<div class="formRow">
                        <?=$this->form->formHomeAddress->line1->renderLabel()?>
                        <?=$this->form->formHomeAddress->line1Input()?>
                        </div>
			<div class="formRow">
                        <?=$this->form->formHomeAddress->line2->renderLabel()?>
                        <?=$this->form->formHomeAddress->line2Input()?>
                        </div>
			<br style="clear:left;"/>
			<div class="formRow">
                        <?=$this->form->formHomeAddress->city->renderLabel()?>
                        <?=$this->form->formHomeAddress->cityInput()?>
                        </div>
			<div class="formRow">
                        <?=$this->form->formHomeAddress->state->renderLabel()?>
                        <?=$this->form->formHomeAddress->stateInput()?>
                        </div>
			<div class="formRow">
                        <?=$this->form->formHomeAddress->postalCode->renderLabel()?>
                        <?=$this->form->formHomeAddress->postalCodeInput()?>
                        </div>
			</fieldset>
			<fieldset><legend>Billing Address</legend>
			<div class="formRow">
                        <?=$this->form->formBillingAddress->line1->renderLabel()?>
                        <?=$this->form->formBillingAddress->line1Input()?>
                        </div>
			<div class="formRow">
                        <?=$this->form->formBillingAddress->line2->renderLabel()?>
                        <?=$this->form->formBillingAddress->line2Input()?>
                        </div>
			<br style="clear:left;"/>
			<div class="formRow">
                        <?=$this->form->formBillingAddress->city->renderLabel()?>
                        <?=$this->form->formBillingAddress->cityInput()?>
                        </div>
			<div class="formRow">
                        <?=$this->form->formBillingAddress->state->renderLabel()?>
                        <?=$this->form->formBillingAddress->stateInput()?>
                        </div>
			<div class="formRow">
                        <?=$this->form->formBillingAddress->postalCode->renderLabel()?>
                        <?=$this->form->formBillingAddress->postalCodeInput()?>
                        </div>
			</fieldset>
<?/*
			<fieldset><legend>Phone Numbers</legend>
			<div class="formRow">
                        <?=$this->form->formPhoneNumber->name->renderLabel()?>
                        <?=$this->form->formPhoneNumber->nameInput()?>
                        </div>
			<div class="formRow">
                        <?=$this->form->formPhoneNumber->number->renderLabel()?>
                        <?=$this->form->formPhoneNumber->numberInput()?>
                        </div>
			</fieldset>
*/?>
			<div style="text-align:right;">
			<?=$this->form->okInput('FormButton')?>
			<!--<input type="submit" />-->
			</div>
			<?=$this->form->renderClose()?>
		</div>
</div>
