<div style="float:left;width:100%;">
	<?=$this->form->renderOpen()?>
	<fieldset><legend><?=__('Building Information')?></legend>
		<div class="formRow" style="padding-top:4px;">
			<?=$this->form->name->renderLabel()?>
			<?=$this->form->nameInput('FormText',array('style'=>'width:200px;'))?>
		</div>
		<br style="clear:left;" />
		<div class="formRow" style="padding-top:4px;">
			<?=$this->form->description->renderLabel()?>
			<?=$this->form->descriptionInput('FormText',array('style'=>'width:200px;'))?>
		</div>
		<br style="clear:left;" />
		<div class="formRow" style="padding-top:4px;">
			<?=$this->form->identifier->renderLabel()?>
			<?=$this->form->identifierInput('FormText',array('style'=>'width:200px;'))?>
		</div>
		<br style="clear:left;" />
		<div class="formRow" style="padding-top:4px;">
			<?=$this->form->facilityCodeId->renderLabel()?>
			<?=$this->form->facilityCodeIdInput('FormText',array('style'=>'width:200px;'))?>
		</div>
		<br style="clear:left;" />
		<div class="formRow" style="padding-top:4px;">
			<?=$this->form->phoneNumber->renderLabel()?>
			<?=$this->form->phoneNumberInput('FormText',array('style'=>'width:200px;'))?>
		</div>
	</fieldset>
	<br style="clear:left;" />
	<div class="formRow" style="float:right;">
		<?=$this->formHidden('enumerationId',$this->enumerationId)?>
		<?=$this->form->idInput('FormHidden')?>
		<?=$this->form->practiceIdInput('FormHidden')?>
		<?=$this->formButton('btnCancel','Cancel',array('onClick'=>'dhxWins.window("windowEditORMObjectId").close();'))?>
		<?=$this->form->okInput('FormButton')?>
	</div>
	<?=$this->form->renderClose()?>
</div>
<script>
function postSubmit<?=$this->form->getId()?>() {
	dhxWins.window("windowEditORMObjectId").close();
	return false;
}
</script>
