<div id="vitalsContainer" style="width:100%;height:100%;overflow:auto;">
	<div id="vitalsListContainer" style="float:left;width:760px;height:300px"></div><br />
	<input type="button" value="Enter New Vitals" onClick="windowAddVitals('vitalsOnAdded')" />
</div>
<br style="clear:left"/>
<div class="formRow">
	<?=$this->formButton('vitalsOK',__('OK'),array('onClick'=>'dhxWins.window("windowSelectVisitId").close()'))?>
	<?=$this->formButton('vitalsCancel',__('Cancel'),array('onClick'=>'dhxWins.window("windowSelectVisitId").close()'))?>
</div>
<script>
function vitalsOnAdded() {
	vitalsListGrid.clearAll();
	vitalsListGrid.load("<?=$this->baseUrl?>/vital-signs.raw/list-patient-vitals?personId="+mainController.getActivePatient(),"json");
}

var vitalsListGrid = new dhtmlXGridObject("vitalsListContainer");
vitalsListGrid.setImagePath("<?=$this->baseUrl?>/img/");
vitalsListGrid.setHeader("<?=__('Data & Time')?>,<?=__('Vital')?>,<?=__('USS Value')?>,<?=__('Metric Value')?>,<?=__('Qualifiers')?>,<?=__('Entering User')?>");
vitalsListGrid.setInitWidths("165,*,*,*,*,*");
vitalsListGrid.setSkin("xp");
vitalsListGrid.init();
vitalsOnAdded();
</script>
