<?=$this->xmlHeader?>
<toolbar>
	<item id="sep0" type="separator"/>
	<item id="check" type="button" img="reload.png" height="45"><![CDATA[<div style="margin:-2px 0 0 5px;"><?=__('Check')?></div>]]></item>
	<item id="apply" type="button" img="save.png" imgdis="save.png" height="45" enabled="false"><![CDATA[<div style="margin:-2px 0 0 5px;"><?=__('Apply')?></div>]]></item>
	<item id="refresh" type="button" img="refresh.png" imgdis="refresh.png" height="45"><![CDATA[<div style="margin:-2px 0 0 5px;"><?=__('Refresh')?></div>]]></item>
</toolbar>
