<script type="text/javascript" src="<?=$this->baseUrl?>/js/custom/common.js"></script>
<?// above code is placed temporarily to fix the loading of richEdit (dhtmlxeditor) ?>

<style>
dt {
	display:inline;
}
dd {
	display:inline;
	padding-right:10px;

}
dl {
}
fieldset {
	padding: 4px;
}
</style>

<div style="background-color: whiteSmoke;padding:10px;height:450px;overflow:scroll;">
<?='';//$this->signatureInfo?>
<?=$this->form?>
<?=$this->form->renderClose(false)?>
<script>
function preSubmitcntemplateform() {
	if (window.transcriptionNotesFormSubmit) {
		var retval = transcriptionNotesFormSubmit();
		if (retval === false) {
			return false;
		}
	}
	return true;
}

function postSubmit<?=$this->form->getId()?>(data) {
	changeCNFilterOptions();
	alert(data);
	return false;
}
</script>
</div>
<?foreach ($this->templateRevisions as $key=>$value):?>
<input type="hidden" name="templateRevisionId[]" value="<?=$key?>|<?=$value?>" />
<?endforeach;?>
<iframe id="iframeprint" style="width:0px;height:0px;margin:0;padding:0;position:relative;float:top;border:none;" />
