<?=$this->xmlHeader?>
<toolbar>
	<item type="button" imgStyle="float:left;" img="no-person-image.png" height="60" width="375" id="tbSelectPatient" title="Selected Patient" disableImage="../images/iconDelete_dis.gif"><![CDATA[ <div style="float:left;text-align:left;"><? if ($this->patient):?><strong><?=utf8_decode($this->patient->lastName)?>, <?=utf8_encode($this->patient->firstName)?> <?=utf8_decode($this->patient->middleInitial)?></strong><br /> <?=__("MRN")?>: <?=$this->patient->recordNumber?> <br /><?=__("Age/Sex")?>:  (<?=$this->patient->person->age?>/<?=$this->patient->displayGender?>) </div><div style="float:left;text-align:left;margin-left:10px;"><?=__("Wt")?>: <?=$this->patient->getWeight()?>  <br /><?=__("Ht")?>: <?=$this->patient->getHeight()?><br /><?=__("BMI/BSA")?>: <?=$this->patient->getBMI()?> (0.00)<? else: ?><strong><?=__("No Patient Selected")?></strong><? endif; ?></div>]]>
</item>
<separator id="div_1"/>
        <item type="button" img="blank.gif" imgStyle="display:none;" height="60" width="300" id="tbSelectVisit" title="Select Admission" disableImage="../images/iconDelete_dis.gif"><![CDATA[ <div style="text-align:left;"><? if($this->visit): ?><strong><?=__("Visit Detail")?></strong> <br /> <?=__("Visitted")?>: <?=date('Y-m-d',strtotime($this->visit->date_of_treatment))?><br />Provider: <?=$this->visit->getProviderDisplayName()?><br /><?=__("Visit Dx")?>: <?=__("None")?> <? else: ?><strong><?=__("Visit Not Selected")?></strong><br /><?=__("Current Loc.")?>:<?//=$this->location->name?><? endif;?></div>]]></item>
<separator id="div_2"/>
	<item type="button" img="blank.gif" imgStyle="display:none;" height="60" width="300" id="tbSelectTeam" title="Select Team" disableImage="../images/iconDelete_dis.gif"><![CDATA[ <div style="text-align:left;"><strong><?=__("Care Team")?></strong><br /><?
if($this->patient):
	if (isset($this->team)):
		echo $this->team;
	else:
		echo __("No team set for this patient, click to select");
	endif;
else:
	echo __("No Patient Selected");
endif;?></div>]]></item>
</toolbar>
