<script>
var dhxWin = new dhtmlXWindows();
dhxWin.setImagePath("<?=$this->baseUrl?>/img/");
dhxWin.setSkin("clear_silver");

function openCommonOrdersWindow() {
	winCommonOrders = dhxWin.createWindow('windowCommonOrders',60,10,320,440);
	winCommonOrders.setText('<?=__('Common Orders')?>');
	var url = '<?=$this->baseUrl?>/orders.raw/list-common-orders';
	winCommonOrders.attachURL(url,true);
	winCommonOrders.setModal(true);
	winCommonOrders.centerOnScreen();
}

function closeCommonOrdersWindow() {
	winCommonOrders.close();
}

function openTextOrdersWindow() {
	winTextOrders = dhxWin.createWindow('windowTextOrders',60,10,350,240);
	winTextOrders.setText('<?=__('Text Only Orders')?>');
	var url = '<?=$this->baseUrl?>/orders.raw/text-orders';
	winTextOrders.attachURL(url,true);
	winTextOrders.setModal(true);
	winTextOrders.centerOnScreen();
}

function closeTextOrdersWindow() {
	winTextOrders.close();
}

</script>

<div>
	<div style="width:20%;float:left;">
	<style>div.gridbox_xp table.obj td {border-bottom: none;border-right:none;}</style>
	<div id="active_orders_container" style="width:100%;height:150px;"></div>
		<script>
		aoGrid = new dhtmlXGridObject('active_orders_container');
		aoGrid.setImagePath("<?=$this->baseUrl?>/img/");
		aoGrid.setHeader('<?=__('Filter')?>');
		aoGrid.setInitWidths("*");
		//alGrid.setColAlign("left");
		aoGrid.setColTypes("ro");
		aoGrid.setSkin("xp");
		aoGrid.attachEvent('onRowSelect',onActiveOrderRowSelected);
		aoGrid.init();
		aoGrid.load('<?=$this->baseUrl?>/orders.raw/filter.json',"json");

		function onActiveOrderRowSelected(rowId,cellIndex) {
			oGrid.clearAll();
			oGrid.load('<?=$this->baseUrl?>/orders.raw/list-orders.json?filter='+rowId,"json");
		}
		</script>
	<div id="write_orders_container" style="width:100%;height:400px;"></div>
		<script>
		woGrid = new dhtmlXGridObject('write_orders_container');
		woGrid.setImagePath("<?=$this->baseUrl?>/img/");
		woGrid.setHeader('<?=__('Write Orders')?>');
		woGrid.setInitWidths("*");
		//alGrid.setColAlign("left");
		woGrid.setColTypes("ro");
		woGrid.setSkin("xp");
		woGrid.attachEvent('onRowSelect',doOnRowSelected);
		woGrid.init();
		woGrid.load('<?=$this->baseUrl?>/orders.raw/write-orders.json',"json");

		function doOnRowSelected(rowId,cellIndex) {
			switch(rowId) {
				case 'common_orders':
					openCommonOrdersWindow();
					break;
				case 'text_orders':
					openTextOrdersWindow();
					break;
			}
		}
		</script>
	</div>
	</div>
	
	<div style="float:left;width:79.5%;">
	<div style="padding-left:5px;padding-top:4px;">
	<div style="float:right;padding-top:2px;padding-bottom:4px;">
		<input type="button" value="View as Tree">
		<input type="button" value="Expand Tree" disabled="disabled">
		<input type="button" value="Collapse Tree" disabled="disabled">
	</div>
	<style>
	.even{
		background-color: white;
	}
	.uneven{
		background-color: ghostwhite;
	}
	</style>
	<div id="orders_container" style="width:100%;height:518px;"></div>
		<script>
		oGrid = new dhtmlXGridObject('orders_container');
		oGrid.setImagePath("<?=$this->baseUrl?>/img/");
		oGrid.setHeader('Service,Status,Order,Start/Stop');
		oGrid.setInitWidths("75,75,*,175");
		//alGrid.setColAlign("left");
		oGrid.setColTypes("ro");
		oGrid.setSkin("xp");
		oGrid.enableAlterCss("even","uneven");
		oGrid.init();
		oGrid.load('<?=$this->baseUrl?>/orders.raw/list-orders.json',"json");
		</script>
	</div>
	</div>
	</div>
</div>

