<?='<?xml version="1.0" ?>'?>
<menu id="0">
	<item id="new" text="<?=__('New Problem')?>" />
	<item id="sep1" type="separator"/>
	<item id="edit" text="<?=__('Edit')?>" enabled="false" />
	<item id="activate" text="<?=__('Activate')?>" enabled="false" />
	<item id="inactivate" text="<?=__('Inactivate')?>" enabled="false" />
	<item id="verify" text="<?=__('Verify')?>" enabled="false" />
	<item id="sep2" type="separator"/>
	<item id="annotate" text="<?=__('Annotate')?>" enabled="false" />
	<item id="sep3" type="separator"/>
	<item id="remove" text="<?=__('Remove')?>" enabled="false" />
	<item id="restore" text="<?=__('Restore')?>" enabled="false" />
	<item id="sep4" type="separator"/>
	<item id="view" text="<?=__('View Details')?>" />
	<!--<item id="show_comments" text="<?=__('Show Comments')?>" type="checkbox" checked="true" enabled="true" />-->
</menu>
