
<div style="width:100%;">
<?if ($this->message) :?>
<div style="background-color:PaleGreen; width:100%;">
<?=$this->message?>
</div>
<?endif;?>

<?=$this->form->renderOpen()?>

<div style="margin-left:10px;">
<?foreach ($this->form->getErrorMessages() as $error) {?>
<?=$error?>
<?}?>
</div>

<div class="formRow" style="padding-top:4px;">
	<?=$this->form->guid->renderLabel()?>
	<?$this->form->guid->setAttrib('size',55)?>
	<?=$this->form->guidInput()?>
</div>
<br style="clear:left;" />
<div class="formRow" style="padding-top:4px;">
	<?=$this->form->name->renderLabel()?>
	<?$this->form->name->setAttrib('size',55)?>
	<?=$this->form->nameInput()?>
</div>
<br style="clear:left;" />
<div class="formRow" style="padding-top:4px;">
	<?=$this->form->type->renderLabel()?>
	<?$this->form->type->setAttrib('size',55)?>
	<?=$this->form->typeInput()?>
</div>
<br style="clear:left;" />
<div class="formRow" style="padding-top:4px;">
	<?=$this->form->connectInfoInput('FormTextarea',array('cols'=>65,'rows'=>14))?>
</div>
<br style="clear:left;" />
<div class="formRow" style="padding-top:4px;">
	<?=$this->formHidden('id',$this->form->dataIntegrationDestinationId->getValue())?>
	<?=$this->form->dataIntegrationDestinationIdInput('FormHidden')?>
	<?=$this->formHidden('type',$this->form->handlerType->getValue())?>
	<?=$this->form->handlerTypeInput('FormHidden')?>
	<?=$this->form->okInput()?>
	<input type="button" value="<?=__("Cancel")?>" onClick="dhxWins.window('winEditDataIntegrationDestinationId').close()"/>
</div>

<script>
function postSubmiteditdestination(data) {
<?if (strlen($this->callback) > 0):?>
	if (window.<?=$this->callback?>) {
		window.<?=$this->callback?>(data);
	}
<?endif;?>
	dhxWins.window('winEditDataIntegrationDestinationId').close();
	return false;
}
</script>

<?=$this->form->renderClose()?>
</div>

