<style>
.insuranceProgram {
        margin: 0em 0.1em;
        border:1px solid #b3b3b3;
        line-height: normal;
        font-size: 100%;
        width: 32em;
}
</style>


<div style="width:100%;">

<?if ($this->message) :?>
<div style="background-color:PaleGreen; width:100%;">
<?=$this->message?>
</div>
<?endif;?>

<?=$this->form->renderOpen()?>

<div style="margin-left:10px;">
<?foreach ($this->form->getErrorMessages() as $error) {?>
<?=$error?>
<?}?>
</div>

<div class="formRow" style="padding-top:4px;">
	<?=$this->form->insuranceProgramId->renderLabel()?>
	<?=$this->formSelect('insurer[insuranceProgramId]',$this->form->insuranceProgramId->getValue(),array('id'=>'insurer-insuranceProgramId','class'=>'insuranceProgram'),$this->insurancePrograms);?>
</div>
<div class="formRow" style="padding-top:4px;">
	<?=$this->form->groupName->renderLabel()?>
	<?$this->form->groupName->setAttrib('class','insuranceProgram')?>
	<?=$this->form->groupNameInput()?>
</div>
<br style="clear:left;" />
<div class="formRow" style="padding-top:4px;">
	<?=$this->form->groupNumber->renderLabel()?>
	<?$this->form->groupNumber->setAttrib('class','insuranceProgram')?>
	<?=$this->form->groupNumberInput()?>
</div>
<br style="clear:left;" />
<div class="formRow" style="padding-top:4px;">
	<?=$this->form->effectiveStart->renderLabel()?>
	<?$this->form->effectiveStart->setAttrib('class','insuranceProgram')?>
	<?=$this->formDateText('insurer[effectiveStart]',$this->form->effectiveStart->getValue(),array('id'=>'insurer-effectiveStart'))?>
</div>
<br style="clear:left;" />
<div class="formRow" style="padding-top:4px;">
	<?=$this->form->effectiveEnd->renderLabel()?>
	<?$this->form->effectiveStart->setAttrib('class','insuranceProgram')?>
	<?=$this->formDateText('insurer[effectiveEnd]',$this->form->effectiveEnd->getValue(),array('id'=>'insurer-effectiveEnd'))?>
</div>
<br style="clear:left;" />
<div class="formRow" style="padding-top:4px;">
	<?=$this->form->assigning->renderLabel()?>
	<?=$this->formSelect('insurer[assigning]',$this->form->assigning->getValue(),array('id'=>'insurer-assigning','class'=>'insuranceProgram'),$this->assigning);?>
</div>
<br style="clear:left;" />
<div class="formRow" style="padding-top:4px;">
	<?=$this->form->copay->renderLabel()?>
	<?$this->form->copay->setAttrib('class','insuranceProgram')?>
	<?=$this->form->copayInput()?>
</div>
<br style="clear:left;" />
<div class="formRow" style="padding-top:4px;">
	<?=$this->form->subscriberId->renderLabel()?>
	<?=$this->formSelect('insurer[subscriberId]',$this->form->subscriberId->getValue(),array('id'=>'insurer-subscriberId','class'=>'insuranceProgram'),$this->subscribers);?>
</div>
<br style="clear:left;" />
<div class="formRow" style="padding-top:4px;">
	<?=$this->form->verified->renderLabel()?>
	<?=$this->form->verifiedInput('FormSelect',array('class'=>'insuranceProgram','options'=>$this->listVerified));?>
</div>
<br style="clear:left;" />
<div class="formRow" style="padding-top:4px;">
	<?=$this->form->active->renderLabel()?>
	<input type="checkbox" name="activeInput" id="activeInput" value="<?=$this->form->active->getValue()?>" helper="formText"<?=($this->form->active->getValue())?' checked="checked"':''?> />
	<?=$this->form->activeInput('FormHidden')?>
</div>
<br style="clear:left;" />
<div class="formRow" style="padding-top:4px;">
	<?=$this->formHidden('id',$this->form->insuredRelationshipId->getValue())?>
	<?=$this->form->personIdInput('FormHidden')?>
	<?=$this->form->insuredRelationshipIdInput('FormHidden')?>
	<?=$this->form->okInput()?>
	<?=$this->formButton('btnCancel',__('Cancel'),array('onclick'=>'dhxWins.window("winEditInsurerId").close()'))?>
</div>

<script>
function preSubmiteditinsurer() {
	var activeInput = dojo.byId("activeInput");
	var activeHiddenInput = dojo.byId("insurer-active");
	var val = 0;
	if (activeInput.checked) {
		val = 1;
	}
	activeHiddenInput.value = val;
	activeInput.checked = false;
	return true;
}

function postSubmiteditinsurer(data) {
	pdInsurersGridReload();
	dhxWins.window("winEditInsurerId").close();
	return false;
}
</script>

<?=$this->form->renderClose()?>

</div>

</div>
