<style>
.insuranceProgram {
        margin: 0em 0.1em;
        border:1px solid #b3b3b3;
        line-height: normal;
        font-size: 100%;
        width: 20em;
}
</style>


<div style="width:100%;">
<?=$this->form->renderOpen()?>

<div class="formRow" style="padding-top:4px;">
	<?=$this->form->insuranceProgramId->renderLabel()?>
	<?=$this->form->insuranceProgramIdInput('FormSelect',array('class'=>'insuranceProgram','options'=>$this->insurancePrograms));?>
</div>
<div class="formRow" style="padding-top:4px;">
	<?=$this->form->groupName->renderLabel()?>
	<?=$this->form->groupNameInput('FormText',array('class'=>'insuranceProgram'))?>
</div>
<br style="clear:left;" />
<div class="formRow" style="padding-top:4px;">
	<?=$this->form->groupNumber->renderLabel()?>
	<?=$this->form->groupNumberInput('FormText',array('class'=>'insuranceProgram'))?>
</div>
<div class="formRow" style="padding-top:4px;">
	<dt><label style="padding-top:4px;"><?=__('Effective Date Range')?> </label></dt>
	<?=$this->form->effectiveStartInput('FormDateText',array('style'=>'width:90px;'))?>
	to <?=$this->form->effectiveEndInput('FormDateText',array('style'=>'width:90px;'))?>
</div>
<br style="clear:left;" />
<div class="formRow" style="padding-top:4px;">
	<?=$this->form->assigning->renderLabel()?>
	<?=$this->form->assigningInput('FormSelect',array('class'=>'insuranceProgram','options'=>$this->assignings));?>
</div>
<div class="formRow" style="padding-top:4px;">
	<?=$this->form->copay->renderLabel()?>
	<?$this->form->copay->setAttrib('class','insuranceProgram')?>
	<?=$this->form->copayInput('FormNumberSpinner',array('places'=>2))?>
</div>
<br style="clear:left;" />
<div class="formRow" style="padding-top:4px;">
	<?=$this->form->subscriberId->renderLabel()?>
	<?=$this->form->subscriberIdInput('FormHidden')?>
	<?=$this->form->subscriberToPatientRelationshipInput('FormSelect',array('class'=>'insuranceProgram','options'=>$this->subscribers));?>
</div>
<div class="formRow" style="padding-top:4px;">
	<?=$this->form->verified->renderLabel()?>
	<?=$this->form->verifiedInput('FormSelect',array('class'=>'insuranceProgram','options'=>$this->listVerified));?>
</div>
<br style="clear:left;" />
<div class="formRow" style="padding-top:4px;">
	<fieldset style="width:450px;"><legend><?=__('Subscriber')?></legend>
		<div style="margin-bottom:10px;">
			<input type="radio" name="subscriberSelectId" id="subscriberPatientSearchId" style="width:20px;" onClick="subscriberPatientSearch()" checked="checked" /> <?=__('Search Current Patients')?> &nbsp;
			<input type="radio" name="subscriberSelectId" id="subscriberPatientNewId" style="width:20px;" onClick="subscriberPatientNew()" /> <?=__('New Patient')?>
		</div>
		<div id="subscriberPatientSearchDivId">
			<?=__('Search')?>: <?=$this->formText('q',$this->q,array('id'=>'q'))?>
		</div>
		<div id="subscriberPatientNewDivId" style="margin-left:100px;">
			<div style="float:left;">
				<?=$this->form->formSubscriber->firstName->renderLabel()?>
				<?=$this->form->formSubscriber->firstNameInput()?>
			</div>
			<div style="float:left;margin-left:10px;">
				<?=$this->form->formSubscriber->lastName->renderLabel()?>
				<?=$this->form->formSubscriber->lastNameInput()?>
			</div>
			<br style="clear:left;" />
			<div style="float:left;">
				<dt><label style="padding-top:4px;"><?=__('SSN')?> </label></dt>
				<?=$this->form->formSubscriber->identifierInput()?>
				<?$this->form->formSubscriber->identifierType->setValue('SSN')?>
				<?=$this->form->formSubscriber->identifierTypeInput('FormHidden')?>
			</div>
			<div style="float:left;margin-left:10px;">
				<?=$this->form->formSubscriber->dateOfBirth->renderLabel()?>
				<?=$this->form->formSubscriber->dateOfBirthInput()?>
			</div>
			<br style="clear:left;" />
			<div style="float:left;">
				<?=$this->form->formSubscriber->gender->renderLabel()?>
				<?=$this->form->formSubscriber->genderInput('FormSelect',array('options'=>Enumeration::getEnumArray('Gender','key')))?>
			</div>
			<div style="float:left;margin-left:10px;">
				<dt><label style="padding-top:4px;"><?=__('Phone#')?> </label></dt>
				<?=$this->formText('subscriber[phone]',null,array('id'=>'subscriber-phone'))?>
			</div>
			<br style="clear:left;" />
			<div style="float:left;">
				<dt><label style="padding-top:4px;"><?=__('Address')?> </label></dt>
				<?=$this->formText('subscriber[address][line1]',null,array('id'=>'subscriber-address-line1'))?>
			</div>
			<div style="float:left;margin-left:10px;">
				<dt><label style="padding-top:4px;">&nbsp;</label></dt>
				<?=$this->formText('subscriber[address][line2]',null,array('id'=>'subscriber-address-line2'))?>
			</div>
			<br style="clear:left;" />
			<div style="float:left;">
				<dt><label style="padding-top:4px;"><?=__('City')?> </label></dt>
				<?=$this->formText('subscriber[address][city]',null,array('id'=>'subscriber-address-city'))?>
			</div>
			<div style="float:left;margin-left:10px;">
				<dt><label style="padding-top:4px;"><?=__('State')?> </label></dt>
				<?=$this->formSelect('subscriber[address][state]',null,array('id'=>'subscriber-address-state'),Address::getStatesList())?>
			</div>
			<br style="clear:left;" />
			<div style="float:left;">
				<dt><label style="padding-top:4px;"><?=__('Zip')?> </label></dt>
				<?=$this->formText('subscriber[address][postalCode]',null,array('id'=>'subscriber-address-postalCode'))?>
			</div>
		</div>
	</fieldset>
</div>
<br style="clear:left;" />
<div class="formRow" style="padding-top:4px;">
	<dt><label for="<?=$this->form->active->getId()?>" class="optional"><?=__('Active')?> <input type="checkbox" name="activeInput" id="activeInput" value="<?=$this->form->active->getValue()?>" helper="formText"<?=($this->form->active->getValue())?' checked="checked"':''?> style="width:30px;" /></label></dt>
	<?=$this->form->activeInput('FormHidden')?>
</div>
<br style="clear:left;" />
<div class="formRow" style="padding-top:4px;">
	<?=$this->formHidden('id',$this->form->insuredRelationshipId->getValue())?>
	<?=$this->form->personIdInput('FormHidden')?>
	<?=$this->form->insuredRelationshipIdInput('FormHidden')?>
	<?=$this->form->okInput()?>
	<?=$this->formButton('btnCancel',__('Cancel'),array('onclick'=>'dhxWins.window("'.$this->form->getWindow().'").close()'))?>
</div>

<?=$this->form->renderClose()?>
</div>

<script>
function preSubmiteditinsurer() {
	var activeInput = dojo.byId("activeInput");
	var val = 0;
	if (activeInput.checked) {
		val = 1;
	}
	var activeHiddenInput = dojo.byId("<?=$this->form->active->getId()?>");
	activeHiddenInput.value = val;
	return true;
}

function postSubmiteditinsurer(data) {
	pdInsurersGridReload();
	dhxWins.window("<?=$this->form->getWindow()?>").close();
	return false;
}

var pscb = dijit.byId("q");
if (pscb != undefined) { 
	pscb.destroyRecursive();
	pscb = null;
}
var psac = new dojox.data.QueryReadStore({
	url:"<?=$this->baseUrl?>/patient.raw/subscriber-auto-complete",
	requestMethod:"get"
},"q");
pscb = new dijit.form.ComboBox({
	name:"q",
	autocomplete:false,
	store:psac,
	hasDownArrow:false,
	value:"<?=$this->q?>"
},"q");
pscb.domNode.style.width = "150px";
dojo.connect(pscb,"onChange",function(arg){
	var subscriber = dojo.byId("<?=$this->form->subscriberId->getId()?>");
	subscriber.value = "";
	if (!this.item) return;
	subscriber.value = this.item.i.label; // .name == arg
});

function subscriberPatientSearch() {
	subscriberToggle(true);
}

function subscriberPatientNew() {
	subscriberToggle(false);
}

function subscriberToggle(search) {
	var state = false;
	if (search) state = true;
	dojo.byId("q").disabled = !state;

	dojo.byId("<?=$this->form->formSubscriber->firstName->getId()?>").disabled = state;
	dojo.byId("<?=$this->form->formSubscriber->lastName->getId()?>").disabled = state;
	dojo.byId("<?=$this->form->formSubscriber->identifier->getId()?>").disabled = state;
	dojo.byId("<?=$this->form->formSubscriber->identifierType->getId()?>").disabled = state;
	dojo.byId("<?=$this->form->formSubscriber->dateOfBirth->getId()?>").disabled = state;
	boxInsurerSubscriberDateOfBirth.setDisabled(state);
	dojo.byId("<?=$this->form->formSubscriber->gender->getId()?>").disabled = state;
	dojo.byId("subscriber-phone").disabled = state;
	dojo.byId("subscriber-address-line1").disabled = state;
	dojo.byId("subscriber-address-line2").disabled = state;
	dojo.byId("subscriber-address-city").disabled = state;
	dojo.byId("subscriber-address-state").disabled = state;
	dojo.byId("subscriber-address-postalCode").disabled = state;
}

subscriberToggle(true);
</script>

