<div id="adminLayout" style="position:relative;float:left;width:100%;height:480px;"></div>
<script>
                var adminLayout = new dhtmlXLayoutObject("adminLayout","2U");
                adminLayout.setImagePath("<?=$this->baseUrl?>/img/");
                adminLayout.cells("a").setText("System Administration");
                adminLayout.cells("a").setWidth(400);
		adminLayout.cells("b").setText('');
                adminLayout.setEffect('collapse',true);
                adminAccordion = adminLayout.cells('a').attachAccordion();
                        adminAccordion.setIconsPath("<?=$this->baseUrl?>/img/");
                        adminAccordion.addItem("systemObjects","System Objects");
			sysObjectsTree = adminAccordion.cells('systemObjects').attachTree();
			sysObjectsTree.setImagePath("<?=$this->baseUrl?>/img/");
			//sysObjectsTree.insertNewChild(0,10,'Barcode Manager');
			sysObjectsTree.attachEvent('onClick',onSystemObjectsTreeItemSelect);
			//sysObjectsTree.insertNewChild(0,2,'Physical Plant');
			//sysObjectsTree.insertNewChild(0,4,'Menu Manager');
			//sysObjectsTree.insertNewChild(0,1,'Data Integration Logs');
			sysObjectsTree.insertNewChild(0,2,'Enumeration Manager');
			//sysObjectsTree.insertNewChild(0,3,'Formulary Manager');
			sysObjectsTree.insertNewChild(0,4,'General Alerts');
			sysObjectsTree.insertNewChild(0,5,'HL7 & Data Integration Manager');
			sysObjectsTree.insertNewChild(0,6,'Health Status Alerts');
			sysObjectsTree.insertNewChild(0,7,"<?=__('Insurance Manager')?>");
			sysObjectsTree.insertNewChild(0,8,'Note Templates');
			sysObjectsTree.insertNewChild(0,9,'NSDR Manager');
			sysObjectsTree.insertNewChild(0,10,'Permissions');
			sysObjectsTree.insertNewChild(0,11,'Persons/Users');
			sysObjectsTree.insertNewChild(0,12,"<?=__('Pharmacy')?>");
			sysObjectsTree.insertNewChild(0,13,'Prescriptions');
			sysObjectsTree.insertNewChild(0,14,'Services');
			sysObjectsTree.insertNewChild(0,15,"<?=__('Update Manager')?>");
			sysObjectsTree.closeAllItems();

                        /*adminAccordion.addItem("healthcloud","HealthCloud");
			healthCloudTree = adminAccordion.cells('healthcloud').attachTree();
			healthCloudTree.setImagePath("<?=$this->baseUrl?>/img/");
			healthCloudTree.insertNewChild(0,1,'CHMED');
			healthCloudTree.attachEvent('onClick',onHealthCloudTreeItemSelect);
			healthCloudTree.insertNewChild(0,2,'CHMED Pharmacies');
			healthCloudTree.closeAllItems();*/

		 adminAccordion.cells("systemObjects").open();

function onSystemObjectsTreeItemSelect(itemId) {
	itemName = sysObjectsTree.getItemText(itemId);
	switch (itemId) {
		case 1: // Data Integration Logs
			break;
		case 2: // Enumeration Manager
			changeAdminContainer(itemName,'<?=$this->baseUrl?>/enumerations-manager.raw');
			break;
		case 3: // Formulary Manager
			changeAdminContainer(itemName,'<?=$this->baseUrl?>/formulary-manager.raw');
			break;
		case 4: // General Alerts
			changeAdminContainer(itemName,'<?=$this->baseUrl?>/general-alerts.raw');
			break;
		case 5: // HL7 & Data Integration Manager
			changeAdminContainer(itemName,'<?=$this->baseUrl?>/admin-hl7.raw');
			break;
		case 6: // Health Status Alerts
			changeAdminContainer(itemName,'<?=$this->baseUrl?>/health-status.raw');
			break;
		case 7: // Insurance Manager
			changeAdminContainer(itemName,'<?=$this->baseUrl?>/insurance-manager.raw');
			break;
		case 8: // Note Templates
			changeAdminContainer(itemName,'<?=$this->baseUrl?>/clinical-notes-manager.raw');
			break;
		case 9: // NSDR Manager
			changeAdminContainer(itemName,'<?=$this->baseUrl?>/nsdr-manager.raw');
			break;
		case 10: // Permissions Templates
			changeAdminContainer(itemName,'<?=$this->baseUrl?>/acl.raw');
			break;
		case 11: // Persons/Users
			changeAdminContainer(itemName,'<?=$this->baseUrl?>/admin-persons.raw');
			break;
		case 12: // Pharmacy
			changeAdminContainer(itemName,'<?=$this->baseUrl?>/admin-pharmacies.raw');
			break;
		case 13: // Prescriptions
			changeAdminContainer(itemName,'<?=$this->baseUrl?>/admin-prescriptions.raw');
			break;
		/*case 99: // Barcode Manager
			changeAdminContainer(itemName,'<?=$this->baseUrl?>/admin-barcode.raw');
			break;*/
		case 14: // Services
			changeAdminContainer(itemName,'<?=$this->baseUrl?>/admin-services.raw');
			break;
		case 15: // Update Manager
			changeAdminContainer(itemName,'<?=$this->baseUrl?>/update-manager.raw');
			break;
		default:
			alert('\'' + itemName + '\' does not have an action defined');
	}
}

function changeAdminContainer(itemName,url) {
	var adminContainerId = 'adminContainerId';
	var oContainer = dojo.byId(adminContainerId);
	if (!oContainer) {
		oContainer = document.createElement('div');
		oContainer.setAttribute('id',adminContainerId);
	}
	dojo.xhrGet({
		url: url,
		handleAs: "text",
		load: function(data,ioArgs) {
			dojo.setInnerHTML(oContainer,data);
			adminLayout.cells("b").attachObject(oContainer);
			adminLayout.cells("b").setText(itemName);
			return data;
		},
		error: function(response, ioArgs) {
			console.error("HTTP status code: ", ioArgs.xhr.status);
			return response;
		}
	});
}

function onHealthCloudTreeItemSelect(itemId) {
	itemName = healthCloudTree.getItemText(itemId);
	switch (itemId) {
		case 1: // CHMED
			break;
		case 2: // CHMED Pharmacies
			changeAdminContainer(itemName,'<?=$this->baseUrl?>/admin-pharmacies.raw');
			break;
		default:
			alert('\'' + itemName + '\' does not have an action defined');
	}
}
</script>
