<?='<?xml version="1.0" encoding="iso-8859-1"?>'?>
<toolbar>
	<item id="newVitals" type="button" img="newproblem.png" height="45"><![CDATA[ <div style="margin-top:-5px;"><?=__('New Vitals')?></div> ]]></item>
	<!--<item id="enteredInError" type="button" img="removeproblem.png" height="45" disabled="disabled"><![CDATA[ <div style="margin-top:-5px;"><?=__('Entered In Error')?></div> ]]></item>
	<item id="pediatricGrowth" type="button" img="filter.png" height="45" disabled="disabled"><![CDATA[ <div style="margin-top:-5px;"><?=__('Pediatric Growth Chart')?></div> ]]></item>-->
</toolbar>
